### ISSUE TITLE
Update Whiteboard images

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#132]

**Comment by Scrubsauce** [comment]
![20150603_081754](https://cloud.githubusercontent.com/assets/2531841/8116480/a5d54f22-103f-11e5-8443-7b224a65616a.jpg)
![20150603_081800](https://cloud.githubusercontent.com/assets/2531841/8116481/a85e3b82-103f-11e5-8383-5a8e44b2254e.jpg)
![20150601_143245 1](https://cloud.githubusercontent.com/assets/2531841/8116484/ad68ad6a-103f-11e5-9281-6ab5920f1f8d.jpg)
![20150603_103205](https://cloud.githubusercontent.com/assets/2531841/8116495/b207a880-103f-11e5-8b60-6671329c93d9.jpg)

**Comment by Scrubsauce** [comment]
![20150610_152913](https://cloud.githubusercontent.com/assets/2531841/8116793/55d776d8-1041-11e5-8062-a9fa4de3b426.jpg)
![20150610_152920](https://cloud.githubusercontent.com/assets/2531841/8116794/55da8f62-1041-11e5-8753-168a0360cc8b.jpg)

![20150603_103200](https://cloud.githubusercontent.com/assets/2531841/8116816/85f3e676-1041-11e5-8188-1c2dfbd239fd.jpg)
![20150603_103156](https://cloud.githubusercontent.com/assets/2531841/8116818/87d74096-1041-11e5-82b0-0a9c0e278dc6.jpg)
![20150603_081806](https://cloud.githubusercontent.com/assets/2531841/8116820/89d9e89e-1041-11e5-9690-c4bc661a6be1.jpg)

**Comment by Scrubsauce** [comment]
Completed

**Comment by Scrubsauce** [comment]
![tigh2](https://cloud.githubusercontent.com/assets/2531841/8135688/59b3df5c-10f6-11e5-9631-22f72b06ed1f.gif)

**Comment by Simulacrum0** [comment]
Original Tigh!

Sober, straight-shooting, and cool under pressure...in many ways i'd take the original crew over the reboot...all 'solidly-decent' folk...

Wonder if he had the first name Saul too?

On 2015_Jun 12, at 13:29EDT, Josh Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

[tigh2]https://cloud.githubusercontent.com/assets/2531841/8135688/59b3df5c-10f6-11e5-9631-22f72b06ed1f.gif

—
Reply to this email directly or view it on GitHubhttps://github.com/mindaptiv/Saul/issues/132#issuecomment-111567533.

Jake Kolb
Founder and Chief Scientist
[http://mindaptiv.com/wp-content/uploads/2015/04/mindaptivLogoHzAllWht1-e1429041435663.png] http://www.mindaptiv.com
Email: Jake@mindaptiv.com
Web: mindaptiv.comhttp://www.mindaptiv.com

CONFIDENTIALITY NOTICE: This e-mail transmission, and any documents, files or previous e-mail messages attached to it may contain information that is confidential or legally privileged. Any unauthorized review, use, disclosure or distribution of such information is prohibited. If you are not the intended recipient, please notify the sender by telephone or return e-mail and delete the original transmission and its attachments and destroy any copies thereof. Thank you.
