### ISSUE TITLE
Produce memory info function

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#18]

**Comment by Scrubsauce** [comment]
Partially completed w/ d1f7ae5e28ac9b70c2d29bd92894eb4f56ca9409

Still need to add total installed memory (requires Context class, same issue as #14)

**Comment by Simulacrum0** [comment]
Given the number of Open Source projects, perhaps something similar to "CPU-Z" is out there under a license that allows us to read/learn from it and grab the memory in a different way, like in the below screenshot ( http://cdn.arstechnica.net/wp-content/uploads/2015/04/Screen-Shot-2015-03-31-at-3_0000_Screen-Shot-2015-03-31-at-7.15.41-PM.jpg )

Reference: 
http://arstechnica.com/gadgets/2015/04/googles-arc-opens-up-to-developers-runs-android-apps-on-most-desktop-oses/

**Comment by Scrubsauce** [comment]
The other leading alternative I've found is to skip the API and go straight to /proc/meminfo using a RandomAccessFile and then parsing through the file to get relevant data and store as an integer, however this will give me the total memory available to the kernel+user space, and not the actual physical size of the RAM installed in the hardware.  Can discuss my work-around Monday for the Context thing because according to the Android API it also retrieves the same value:

"The total memory accessible by the kernel. This is basically the RAM size of the device, not including below-kernel fixed allocations like DMA buffers, RAM for the baseband CPU, etc."

**Comment by Simulacrum0** [comment]
We can work w/ RAM of device...at least it gives a sense of what to ask for, plan for...half the time the avail mem isn't available anyways...but it guides choices-

Seems best for now-

**Comment by Scrubsauce** [comment]
Completed as of 2b7774f12c9a53146a82671cf966f84e60f1d82e

Now also grab:
-Installed memory in bytes
-Available memory in bytes
-Low memory threshold in bytes
-Is memory low? value
