### ISSUE TITLE
Status Update1/5

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#185]

**Comment by Simulacrum0** [comment]
1) Cool...i dig MIDI as a massive-button controller w/ 'acceleration-keys'...like the best of the PS3 buttons+
2)  Thanks Josh...really appreciate all the work-!
![1385403965_water-640x242](https://cloud.githubusercontent.com/assets/8696781/12132296/8f69312a-b3e8-11e5-8dee-a3b6cf51069f.jpg)
