### ISSUE TITLE
Produce input devices function

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#19]

**Comment by Scrubsauce** [comment]
Initial grabbing of InputDevice objects as of 68ac3d60837b3a891563ebfc76681e6f4d08d8ca

**Comment by Scrubsauce** [comment]
Android Source Bitmask for classes/types:
![20150401_125633](https://cloud.githubusercontent.com/assets/2531841/6967540/27a9429c-d91d-11e4-8190-be5ee15ae373.jpg)

**Comment by Scrubsauce** [comment]
Special:
0xffffff00 ANY

Classes:
0x00000000 NONE CLASS
0x00000001 BUTTON CLASS
0x00000002 POINTER CLASS
0x00000004 TRACKBALL CLASS
0x00000008 POSITION CLASS
0x00000010 JOYSTICK CLASS
0x000000ff MASK CLASS

Types:
0x00000000 UNKNOWN
0x00000101 KEYBOARD
0x00000201 DPAD
0x00000401 GAMEPAD
0x00001002 TOUCH SCREEN
0x00002002 MOUSE
0x00004002 STYLUS
0x00010004 TRACKBALL
0x00100008 TOUCHPAD
0x00200000 TOUCH NAVIGATION
0x01000010 JOYSTICK
0x02000001 HDMI

**Comment by Scrubsauce** [comment]
@Simulacrum0 do we care to retrieve the VendorID of a device (if available)?  If yes, should I just assume we leave it with a default value on platforms or devices where we can't find the vid?

**Comment by Scrubsauce** [comment]
@Simulacrum0  same question, but for virtual devices (Android also supports virtualized InputDevices, should we notate if a device is virtual or not in deviceStruct?).

**Comment by Simulacrum0** [comment]
"Virtual" input seems unneeded if we enumerate and capture the 'actual' device. ( no reason to have the actual device/ranges and various virtual or emulated interpretations...).  Unless i'm missing something-

Definitely grab Vendor ID ( HID value is universal and allows us to match across platforms/devices ).  Should be Vendor & Device ID actually...like a Make & Model...

**Comment by Scrubsauce** [comment]
Roger on vid, reply on virtual:

In the case of the SHIELD an example of one of the returned input devices was the virtual keyboard Android uses for texting/browsing/tweeting/what-have-you.  Since there is no physical representation of this device I was assuming it'd be best to store it with the rest of the devices since apps can still access it as a keyboard, despite the fact that it doesn't actual exist irl.  

Android's InputDevice class has a member variable `boolean isVirtual` (or something to that effect).  We could add our own boolean/integer value to cylonStruct to notate if the device is virtual or just not worry about it.

**Comment by Scrubsauce** [comment]
Retrieval of non-controller devices from Android API InputDevice class complete as of 890dd812e3509cb46b4181dacd4967e12b75a928

**Comment by Scrubsauce** [comment]
vendorID supported as of d12f9b4e8652f749a2c92a18ba6f3abee8150bf8

NOTE: this will only work for devices on KitKat or later.

**Comment by Scrubsauce** [comment]
controller retrieval is partially done as of a58e2e32a64bf37cd3b1807571a3154ded0afc8f

NOTE: userIndex will only retrieve for KitKat or later

**Comment by Simulacrum0** [comment]
Perhaps the best way of handling this is to allow 1 ( aka '1st polled' ) virtual device for keyboard ( for text input ) and ignore others for now.  If the SHIELD can offer a virtual mouse, virtual trackpad, virtual touchscreen, etc. but also can just post motion vectors/touch points on its contact surface, then that's all we'd like to get from polling...aka 'just the SHIELD'.  Perhaps i'm misunderstanding the rules/scope of the virtual stuff?

Will discuss in depth at 9MST-

**Comment by Scrubsauce** [comment]
Bitmask used by cylonStruct and XINPUT
![20150403_150703](https://cloud.githubusercontent.com/assets/2531841/7005940/2cd9a214-dc3a-11e4-8bcc-e910ced7315a.jpg)

**Comment by Scrubsauce** [comment]
Trigger and Thumbstick values table:
![20150403_150658](https://cloud.githubusercontent.com/assets/2531841/7005952/46ff1944-dc3a-11e4-84ba-8b8d68494146.jpg)

**Comment by Scrubsauce** [comment]
`les`

**Comment by Scrubsauce** [comment]
``maybe``

**Comment by Simulacrum0** [comment]
#define One_f 1.f
#define Max_su 65535
#define RcpSu_f ( One_f / Max_su )

// Rcp = Reciprocal 
#define Rcp2_f 0.5f

// Convert Short Ints to Floats
// supporting different ranges

#define fSi( _si ) (( float )( _si ))
#define fnSni( _sni ) (( 1.f + ( 2.f \* fSi( _sni )) ) \* RcpSu_f )
#define faSni( _sni ) ((( 1.f + ( 2.f \* fSi( _sni )) ) \* RcpSu_f ) \* Rcp2_f + Rcp2_f )

**Comment by Scrubsauce** [comment]
![](http://biosector01.com/wiki/images/3/31/Nuhvok_Krana_Su.png)

**Comment by Scrubsauce** [comment]
![](http://i.ebayimg.com/images/i/121069173060-0-1/s-l1000.jpg)

**Comment by Simulacrum0** [comment]
fa = float 'Amount' 0..+1
fn = float 'Normalized' -1...+1 

su = short unsigned int
sa = short unsigned int as 'Amount' ( remapping 0...65535 to 0...+1 )
sn = short UNsigned int 'Normalized( remapping 0...65535 to -1...+1)'
sni = short signed int 'Nnormalized ( remapping -32768...32767 to -1..+1 )'

**Comment by Scrubsauce** [comment]
Will be using KeyEvent's for controller state as discussed in #36

**Comment by Scrubsauce** [comment]
Partial KeyEvent handling implemented as of aecb94817defcc1e424fa4de7e2252b77734f75e

Rehauled logging for the test application, but still need to apply it to the old stuff I was writing using system.out.  Can now see each key in console as its pressed on keyboard AND controller.  

Next steps-
1. Standardize all the logging.
2. Reprint controller bitmask at runtime when it changes to demonstrate that it changes in real time.
3. Add additional action logic to determine if a button is being released or depressed to determine whether or not an event should erase/set the given bit in the controller's state mask.

**Comment by Scrubsauce** [comment]
Key pressed/release detection code started w/ 630058756b20f29e26f6fb65c1d0bf5ed9c3edd1

**Comment by Scrubsauce** [comment]
Whiteboard for Button Pressed/Released Logic:
![20150408_113011](https://cloud.githubusercontent.com/assets/2531841/7051126/232a671c-dde3-11e4-8c76-77e10863d6e0.jpg)

**Comment by Scrubsauce** [comment]
Controller button mask updating complete as of 837e2ed7e090593f7f3360f112a562de59eeafa1
-Controller creation complete
--InputDevice retrieval and storage complete
---Requirement complete
