### ISSUE TITLE
test 2

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#2]
test 2

**Comment by Scrubsauce** [comment]
![20150316_134447](https://cloud.githubusercontent.com/assets/2531841/6674974/0ff5d0d0-cbe3-11e4-8c74-d2f6f9c6f867.jpg)

**Comment by Scrubsauce** [comment]
![20150317_151532](https://cloud.githubusercontent.com/assets/2531841/6697831/f23cebf6-ccb8-11e4-9ccc-306e234dba82.jpg)

**Comment by Scrubsauce** [comment]
![20150407_104031](https://cloud.githubusercontent.com/assets/2531841/7028532/9308da1c-dd13-11e4-85e2-a73ac62b9bca.jpg)

**Comment by Scrubsauce** [comment]
![20150409_092521](https://cloud.githubusercontent.com/assets/2531841/7070212/b6cd08fa-de9a-11e4-841b-a4e93b06f83d.jpg)

**Comment by Scrubsauce** [comment]
![20150414_141304](https://cloud.githubusercontent.com/assets/2531841/7146432/b5616e10-e2b0-11e4-96ed-b69cd96f8d1d.jpg)

**Comment by Scrubsauce** [comment]
![cylon](https://cloud.githubusercontent.com/assets/2531841/7208432/fac5f8d2-e4fd-11e4-97ba-cd03d89ab549.jpg)

**Comment by Scrubsauce** [comment]
![saul](https://cloud.githubusercontent.com/assets/2531841/7209375/6c76a3f8-e505-11e4-8043-6fa1d1f1be33.jpg)

**Comment by Simulacrum0** [comment]
Love the Centurions-
Such interesting design evolution from the originals...and love when they demand their rights-

**Comment by Simulacrum0** [comment]
Time for a drink Saul...

**Comment by Scrubsauce** [comment]
You've found my secret image uploading issue!  (for some reason haven't been able to upload directly into wiki, so I use a thread instead)

**Comment by Simulacrum0** [comment]
Weird thing is, using "Markdown" should just work...just plain (insert-expletive) text w/ the bracket markers...but GitHub doesn't seem to follow it consistently ( or i'm missing that consistency ).  We export reports from Essence to .md ( as well as .pdf, .yaml, .json, .txt, etc. ) and picture, links, and 'code' shows as expected when viewed in LightRoom or the OS X .md plugin, but not on Github using cut'n'paste.  Seemingly something inconsistent in this space-

**Comment by Scrubsauce** [comment]
![20150423_112420](https://cloud.githubusercontent.com/assets/2531841/7303340/2449209a-e9ad-11e4-8aee-4ed44ab67aab.jpg)
![20150423_112312](https://cloud.githubusercontent.com/assets/2531841/7303344/25413fe6-e9ad-11e4-951b-e175debafa80.jpg)

**Comment by Scrubsauce** [comment]
![20150507_104936](https://cloud.githubusercontent.com/assets/2531841/7520873/302ec4aa-f4a7-11e4-90bb-dd423519e67b.jpg)

**Comment by Scrubsauce** [comment]
![20150601_143245](https://cloud.githubusercontent.com/assets/2531841/7922763/95ebaec0-086b-11e5-9e88-1ca06e9b524a.jpg)

**Comment by Simulacrum0** [comment]
Nice look...you're headed into Alex-Grey-Art territory...

**Comment by Scrubsauce** [comment]
![20150706_124849](https://cloud.githubusercontent.com/assets/2531841/8532121/3bcb1e96-23e9-11e5-9c63-a64cf49a2b4d.jpg)
![20150706_124901](https://cloud.githubusercontent.com/assets/2531841/8532122/3bcd7218-23e9-11e5-80ad-f30dc28944ed.jpg)

**Comment by Scrubsauce** [comment]
lmnop

**Comment by Scrubsauce** [comment]
![image](https://cloud.githubusercontent.com/assets/2531841/8532169/976ed4ea-23e9-11e5-8e5a-ee1e3c7a6b6b.png)
