### ISSUE TITLE
Main Activity/View Dispatch Continues After Close

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#41]
Could not reproduce but even after uninstalling test app, logcat was still registering dumped KeyEvents that had nowhere to go due to the View losing focus.  Should keep in mind when coding Main Activity for future products that integrate w/ Saul (may need to add a finish() function when app is closed to reclaim any resources used by Views).

**Comment by Scrubsauce** [comment]
3 weeks of watching for this and have yet to re-create it.

**Comment by Simulacrum0** [comment]
Perhaps only a random bug with system corruption? ( often that's unlikely, but who knows?? )
