### ISSUE TITLE
Produce Display Devices

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#44]
producer for Display class objects available to current device.

**Comment by Scrubsauce** [comment]
Retrieving primary display (but via array method so other displays should be supported, just need to test for externals) from android API and calculating its preferred/current/native orientation as of 61131e73bf4aaf6dcc236663162127644ca04d2f

**Comment by Scrubsauce** [comment]
Mapping retrieved display devices metadata to Device objects, which are in turn mapped to Display objects just like in Foster as of 82ad8bcd9b1ad2941c5216715848383f51c69927

**Comment by Scrubsauce** [comment]
Logging for detected Display objects added as of 82ad8bcd9b1ad2941c5216715848383f51c69927

**Comment by Scrubsauce** [comment]
Super/Parent device is now tied directly to the corresponding Device for a given Display as of 2e4a21beedae29dee4790988b13f3f52be370d65

**Comment by Scrubsauce** [comment]
@Simulacrum0  Stereoscopic 3D apparently not fully supported in Android across all devices yet?  Planning on setting our values to false for the time being since the API doesn't always have access to this information.  More dependent on the hardware manufacturer if you have access to that sort of stuff in code:
http://www.htcdev.com/devcenter/s3d
Camera 0 = Camera.CameraInfo.CAMERA_FACING_BACK (as of Android 2.3)
Camera 1 = Camera.CameraInfo.CAMERA_FACING_FRONT (as of Android 2.3)
Camera 2 = undefined in Android platform, HTC specific value for stereoscopic camera mode (both rear facing cameras)

**Comment by Scrubsauce** [comment]
Default isStereoscopicEnabled value is set to 0 as of 51dc3834928ce0622c824f4cb996682365128324

**Comment by Scrubsauce** [comment]
Next steps:
-DPI (rawX, rawY, logical)
-resolution scale (how if even can we map to Windows values?)

**Comment by Scrubsauce** [comment]
Whiteboard notes on Android DPI enum values ( @Simulacrum0  may be good for future reference on your end as well?)
![20150414_130204](https://cloud.githubusercontent.com/assets/2531841/7145102/02b8b6dc-e2a7-11e4-98b4-fd71d0bdfd44.jpg)

**Comment by Scrubsauce** [comment]
Updated whiteboard image above.

**Comment by Scrubsauce** [comment]
Scales and DPI values added as of 90e74cf721da26e067d45c51decdd4b6144e93f3  task complete

**Comment by Simulacrum0** [comment]
Wonder why we don't just get a list of screens with physical dimensions and then a list of 'resolutions/refresh-rates/color-depths/etc'...odd that there's a fixed metric table instead of 'do the division yourself'...must be about resource-targeting or something with a design oriented purpose?
