### ISSUE TITLE
4K TV Testing w/ Shield and Display Devices

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#51]
Did 4K testing today, if I understand Nvidia's docs correctly it sounds like the SHIELD tablet can only export 1080 through HDMI.  But ran the device with the Saul test app on SHIELD in console mode (then changed TV's native resolution over several tests) and then ran the test app on SHIELD in mirror mode (again, changed TV's native resolution over several tests).  

Changing TV's resolution either while running, between runs, or between connections (unplug SHIELD,  change TV settings, then reconnect) all failed to change the DPI retrieved for any display devices.

Running in console mode only returned a single display device (presumably the tv).

Running in mirror mode returned two display devices (presumably the tv and the tablet) with two different DPI's.

**Comment by Simulacrum0** [comment]
bummer.
Are you at least able to retrieve the res?

**Comment by Scrubsauce** [comment]
Yeah I'm getting the raw DPI (horizontal and vertical, they change depending on the display mode) and the logical DPI of the whole display (usually 320).

**Comment by Simulacrum0** [comment]
Well, that should give us enough to make some guesses at least...wish there was the simple yet useful EDID info in stock form-
