### ISSUE TITLE
Convert Cylon Data Native Code via JNI + NDK

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Saul#91]
^

**Comment by Scrubsauce** [comment]
Initial working test code pushed w/ d5a1dbc3c299a3110931aa1a8eed428427325e5a

**Comment by Scrubsauce** [comment]
Relocated static library load call from test activity class to Cylon class w/ 063b36e8e08a60cb5776e2b3023e7c7ac1095418

**Comment by Scrubsauce** [comment]
@Simulacrum0 !!!
![nativelog](https://cloud.githubusercontent.com/assets/2531841/7891132/dd2b6994-0607-11e5-911e-e1480c5cc5b5.png)

**Comment by Scrubsauce** [comment]
Wboard notes:
![20150529_140240](https://cloud.githubusercontent.com/assets/2531841/7891694/f846b676-060b-11e5-8dfe-0c8a1e098a1f.jpg)

**Comment by Scrubsauce** [comment]
Next steps:
1. Incorporate cylonStruct and support structures into JNI codebase.
2. Populate a cylonStruct with Cylon.java data.
3. Return log messages to Cylon.java.

**Comment by Scrubsauce** [comment]
Native Activity class:  http://developer.android.com/reference/android/app/NativeActivity.html

**Comment by Scrubsauce** [comment]
@Simulacrum0 this will be an important resource going forward, a cheat sheet for the native API (what we get).  For the stuff that was previously only in Java you get a native way to handle activities, windows, asset management, etc.  Looks like the NDK has been relatively stable for several years, with minimal additions since then.
http://mobilepearls.com/labs/native-android-api/

**Comment by Simulacrum0** [comment]
Looking good...glad to see the low amount of redirects/alterations in the NDK...much peace in reading that-

**Comment by Simulacrum0** [comment]
Looks like we'll use much of this...probably not Zip ( except if there's a format embedding it, like TIFF )...OpenGLES variants, dynamic loader, OpenSL, AL, input/sensor/events...

Definitely glad to see "AndroidBitmap_lockPixels" for access to system visuals handed to us.

Looks a lot cleaner than iOS so far...but they reorder a lot per update...so who knows...

**Comment by Scrubsauce** [comment]
Had a lot of hardship today with imports, finally resolved (or seems to be, I hope...) using this link http://permadi.com/blog/2011/09/setting-up-android-jni-projects-in-windows-eclipse-and-sequoyah/

**Comment by Scrubsauce** [comment]
mapping with getters and setters between two languages
http://stackoverflow.com/questions/3923299/how-to-pass-c-structs-back-and-forth-to-java-code-in-jni

**Comment by Scrubsauce** [comment]
JNI types: http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html

**Comment by Scrubsauce** [comment]
std::string jstring converting http://stackoverflow.com/questions/8322208/syntax-for-converting-jstring-and-appending

**Comment by Scrubsauce** [comment]
@Simulacrum0:  

06-04 13:00:18.723: I/Saul(18287): REPORT:
06-04 13:00:18.723: I/Saul(18287): Cylon: com.mindaptiv.saul.Cylon@42173ff8
06-04 13:00:18.723: I/Saul(18287): Username: Scrub
06-04 13:00:18.753: D/Saul(18287): NDK:LC: Scrub
06-04 13:00:18.753: I/Saul(18287): Scrub

**Comment by Scrubsauce** [comment]
@Simulacrum0 
1st Scrub is from the Java side of code as a Java.lang.String object.  
2nd Scrub is the Java data converted in NDK via JNI into a C++ const char\* (NDK logging method won't accept std::strings) and printed from within the native method.  
3rd Scrub is the Java  data converted into a C++ std::string and then converted AGAIN back into a Java String object and sent back to the Java code for printing.

Seems like character data is finally converting (and in a 2-way manner now if need be) without any hang ups or weird malformation of the data.

**Comment by Scrubsauce** [comment]
First C++ native code (previous push was pure C) w/ STL includes + std::string retrieval in native code pushed w/ 0a06ffea32fdc589126ac20302da8cac455ec0d3

**Comment by Scrubsauce** [comment]
Progress as of: e1da474e06df5df6ef59f434dccf33f41b188d5d
Various additions made to include new Android specific metadata items to the cylonStruct added, additionally all Java Strings and Java Integers are now being converted and stored into a native cylonStruct.

**Comment by Scrubsauce** [comment]
Type signatures: http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html

**Comment by Scrubsauce** [comment]
cylonStruct float and long values are complete as of 7862cbb7c69754e4d2305e7292fdcfc93340cc7a

**Comment by Scrubsauce** [comment]
Next steps:
1. Support structs and lists of the support structs in a given cylonStruct

**Comment by Scrubsauce** [comment]
Cylon -> cylonStruct progress graph
![20150608_105955](https://cloud.githubusercontent.com/assets/2531841/8040700/b521f772-0dcf-11e5-91bd-f1d2a81385a4.jpg)

**Comment by Scrubsauce** [comment]
fixed floats and completed deviceStructs as of 39648afb5af6cb4e0b3b80411ef93525380a7665

**Comment by Scrubsauce** [comment]
Completed controllerStructs (even their paired, inner deviceStructs) as of dab4cbd2e01c1ea4b914e09d6badd2213d6dca22

**Comment by Scrubsauce** [comment]
Completed displayStructs as of b3cc21f42d3f3985adca0c3866f4ea8aa173bc46

**Comment by Scrubsauce** [comment]
Completed sensorStructs as of cd28a282eef8a27e578dad8f2dacd418c869a5cb

**Comment by Scrubsauce** [comment]
Completed storageStructs as of 1c32b51db843a69a55ef0a382553330a145bae66
Task complete

**Comment by Scrubsauce** [comment]
Whiteboard:
![20150610_152913](https://cloud.githubusercontent.com/assets/2531841/8116793/55d776d8-1041-11e5-8062-a9fa4de3b426.jpg)
![20150610_152920](https://cloud.githubusercontent.com/assets/2531841/8116794/55da8f62-1041-11e5-8753-168a0360cc8b.jpg)
